//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College_Registration.Business.Logic.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentRecord
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string Batch { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailId { get; set; }
    
        public virtual tblCourse tblCourse { get; set; }
        public virtual tblYear tblYear { get; set; }
    }
}
